<br>

### Phage prediction by contig

<br>

#### **Phage prediction table**


**Tab. 1:** Interactive phage prediction table. The scores/p-values of each column can be filtered.
The adjusted table can be exported as a .csv, .pdf or .excel.

```{r, echo=FALSE}
suppressMessages(library(DT))
suppressMessages(library(dplyr))
suppressMessages(library(tidyr))

input_file_heatmap <- "#RESULTSENV#"
sample_name <- "#NAMEENV#"

dt = read.table(file = input_file_heatmap, sep = '\t', header = TRUE)

wide <- spread(dt, toolname, p_value)

col_count = ncol(wide)-1
wide3 = wide %>% 
    replace(is.na(.), 0) %>%
    mutate(sum_normed = rowSums(across(where(is.numeric)))/col_count) %>%   # norm sum of pvalue of tooles
    mutate_if(is.numeric,
            round,
            digits = 3)
## pre sort table
wide3 <- wide3 %>% 
 # desc orders from largest to smallest
  arrange(desc(sum_normed))

datatable(wide3, rownames = TRUE , class = 'hover', extensions  = 'Buttons', filter = "top", options = list(
    dom = 'Bfrtip', buttons = c('copy', 'csv', 'excel', 'pdf', 'colvis'))) %>% formatStyle(names(wide3),
  background = styleColorBar(range(wide3[,-1]), 'lightblue'),
  backgroundSize = '98% 88%',
  backgroundRepeat = 'no-repeat',
  backgroundPosition = 'center')

##columnDefs = list(list(visible=FALSE, targets=col_count+1) ## hides last column

```


#### **How to interpret the data**

<style>
div.blue { background-color:#e6f0ff; border-radius: 5px; padding: 20px;}
</style>
<div class = "blue">
WtP uses several phage prediction tools that work differently and generate different outputs. 
Contigs with the overall highest p-values/scores are displayed at the top, and contigs with low p-values/scores are at the bottom of the table.
Each tool's p-value/score can be individually adjusted and filtered in Table 1. 
Some tools don't generate p-values or scores as output; instead, they generate categories with likelihoods or directly predict and assign the contigs as phage.  
The tool's output and what WtP assigns are shown in the table below.
   
</div>

#### **Explanation tool output**

**Tab.2**: The output of each tool and the values WtP assigns in Tab.1 .
  
Tool            | Standard output                     | WtP displayed value | F1 scores by Ho et al.
|-|-|-|-|
|deepvirfinder  | p-value: 0 to 1                      | 0 to 1      | >0.83
|metaphinder    | string: phage                        | 1           | >0.83
|metaphinder own| string: phage                        | 1           | N/A
|phigaro        | score: 0 to 1                        | 0 to 1      | N/A
|pprmeta        | phage_score: 0 to 1                  | 0 to 1      | 0.92
|seeker         | score: 0 to 1                        | 0 to 1      | <0.5
|sourmash       | similarity: 0 to 1                   | 0 to 1      | N/A
|vibrant        | prediction: virus                    | 1           | >0.83
|vibrant-virome | prediction: virus                    | 1           | N/A
|virfinder      | p-value: 0 to 1                      | 0 to 1      | >0.83
|virnet         | score: 0 to 1                        | 0 to 1      | N/A
|virsorter      | category 1, category 2, category 3   | 1, 0.5, 0   | >0.83
|virsorter-virome|category 1, category 2, category 3   | 1, 0.5, 0   | N/A
|virsorter2     | dsDNAphage: 0 to 1                   | 0 to 1      | 0.93


#### **Extract contigs of interest**

<style>
div.blue { background-color:#e6f0ff; border-radius: 5px; padding: 20px;}
</style>
<div class = "blue">
```shell
# Filter the Phage prediction by contig table to your liking   
# Click on the CSV-Button (this will download the Phage prediction by contig table)     
# Open your Linux-Terminal     
mkdir contigs_of_interest 
cd  contigs_of_interest  
# Copy the downloaded Phage prediction by contig table to the contigs_of_interest -folder  
# Copy the input_fasta to the contigs_of_interest -folder  
cp WtP_results/your_sample/Input_fasta/your_input_fasta.fa.gz /foo/bar/contigs_of_interest  
# Get contig IDs of interest  
tail -n+2 final_report.utf8.csv | tr -d '"' | cut -f2 -d"," > contig_IDs_of_interest.txt  
# via Docker: use Seqkit to extract contigs of interest of your input fasta-file  
docker run --rm -it -v $PWD:/input nanozoo/seqkit:0.13.2--cd66104  
cd input  
seqkit grep --pattern-file contig_IDs_of_interest.txt your_input_fasta.fa.gz > contigs_of_interest.fa    
# Finally, close the docker with ctrl + d  
```   
</div>




<a href="#top">Back to top</a>
