### x-y_tools

<style>
div.blue { background-color:#e6f0ff; border-radius: 5px; padding: 20px;}
</style>
<div class = "blue">
**Note:**   
In this section you will find all contigs that meet the following requirements:  
p-value >= 0.5     
</div>


#### **CheckV output**
```{r, echo=FALSE}
du = read.table(file = 'T7_draft/CheckV/T7_draft_quality_summary.tsv', sep = '\t', header = TRUE)

datatable(du, rownames = FALSE, class = 'hover', extensions  = 'Buttons', options = list(
    dom = 'Bfrtip', buttons = c('copy', 'csv', 'excel', 'pdf', 'colvis')))

```


#### **Annotation table**
```{r, echo=FALSE}
dv = read.table(file = 'T7_draft/annotation_results/small/annotationfile.tbl', sep = '\t', header = FALSE)
colnames(dv) <- c("gene_prediction","contig_name","start","end","category")
datatable(dv, rownames = FALSE, class = 'hover', extensions  = 'Buttons', options = list(
    dom = 'Bfrtip', buttons = c('copy', 'csv', 'excel', 'pdf', 'colvis')))
```


#### tax classification

contig|  prediction_value|        predicted_organism_name|
|-|-|-|
ctg1_len=102949 0.53    gi_265524965_gb_GU071091.1___Enterobacteria__phage__T7,__complete__genome 

<a href="#top">Back to top</a>